# Generated by Django 4.0.5 on 2022-07-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionedproduct',
            name='bid_id',
            field=models.IntegerField(default=-1),
        ),
    ]
