# Generated by Django 4.0.5 on 2022-07-03 02:43

import auction.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_bidder_balance_alter_bidder_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), auction.models.only_int]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), auction.models.only_int]),
        ),
    ]
