# Generated by Django 4.0.5 on 2022-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionedproduct_bid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('FAIL', 'failed'), ('SUCCESS', 'success')], max_length=10, null=True),
        ),
    ]
