# Generated by Django 4.0.5 on 2022-07-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='membership',
        ),
        migrations.AddField(
            model_name='bidder',
            name='balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.DeleteModel(
            name='MemberFees',
        ),
    ]
