# Generated by Django 4.0.5 on 2022-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_bidder_first_name_bidder_last_name_seller_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
